# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
    branches:
        include:
        - '*'  # must quote since "*" is a YAML reserved character; we want a string

stages:
  - stage: Build
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: BuildJob
        steps:
        - task: Gradle@2
          displayName: 'Gradle build'
          inputs:
            gradleWrapperFile: 'gradlew'
            options: '-x lint'
            tasks: 'build'
            publishJUnitResults: false
            testResultsFiles: '**/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            sonarQubeRunAnalysis: false
  - stage: Test
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: TestJob
        steps:
        - task: Gradle@2
          displayName: 'Gradle test'
          inputs:
            gradleWrapperFile: 'gradlew'
            tasks: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            sonarQubeRunAnalysis: false
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/TEST-*.xml'
  - stage: Inspect
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: InspectJob
        steps:
        
        - task: Gradle@2
          displayName: 'Gradle lint'
          inputs:
            gradleWrapperFile: 'gradlew'
            tasks: 'lint'
            publishJUnitResults: false
            testResultsFiles: '**/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            sonarQubeRunAnalysis: false
